In [1]:
#importing all the files one by one

In [2]:
import pandas as pd
file1=pd.read_csv(r"C:\Users\SATHVIK\OneDrive\Desktop\project-1\olist_customers_dataset.csv")
file1.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [4]:
#analyzing the file 1 data and cleaning stuff
#1.checking null values
file1.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [9]:
#2.checking whehter we have duplicate customers or not (customer_id ,must be unique)
print(file1["customer_id"].shape)
print(file1["customer_id"].nunique())

(99441,)
99441

In [27]:
#checking about customer unique id
print(file1["customer_unique_id"].nunique())
print(file1.duplicated().sum())

96096
0

In [3]:
#checking 2nd file
file2=pd.read_csv(r"C:\Users\SATHVIK\OneDrive\Desktop\project-1\olist_geolocation_dataset.csv")
file2.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [4]:
file2.isnull().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [7]:
#renaming some columns
file2=file2.rename(columns={"geolocation_lat":"latitude"})
file2.head()

,geolocation_zip_code_prefix,latitude,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [8]:
file2=file2.rename(columns={"geolocation_lng":"longitude"})
file2.head()

,geolocation_zip_code_prefix,latitude,longitude,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [9]:
file2.describe()

       geolocation_zip_code_prefix      latitude     longitude
count                 1.000163e+06  1.000163e+06  1.000163e+06
mean                  3.657417e+04 -2.117615e+01 -4.639054e+01
std                   3.054934e+04  5.715866e+00  4.269748e+00
min                   1.001000e+03 -3.660537e+01 -1.014668e+02
25%                   1.107500e+04 -2.360355e+01 -4.857317e+01
50%                   2.653000e+04 -2.291938e+01 -4.663788e+01
75%                   6.350400e+04 -1.997962e+01 -4.376771e+01
max                   9.999000e+04  4.506593e+01  1.211054e+02

In [10]:
file2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   latitude                     1000163 non-null  float64
 2   longitude                    1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object
 4   geolocation_state            1000163 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 38.2+ MB

In [13]:
print(file2["latitude"].nunique())
print(file2["latitude"].shape)

717360
(1000163,)

In [26]:
print(file2["geolocation_zip_code_prefix"].nunique())
print(file2["geolocation_zip_code_prefix"].shape)
print(file3.duplicated().sum())

19015
(1000163,)
0

In [17]:
file3=pd.read_csv(r"C:\Users\SATHVIK\OneDrive\Desktop\project-1\olist_order_items_dataset.csv")
file3.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [25]:
print(file3["order_id"].nunique())
print(file3["order_id"].count())
print(file3.duplicated().sum()) #no duplicate rows

98666
112650
0

In [28]:
#next file
file4=pd.read_csv(r"C:\Users\SATHVIK\OneDrive\Desktop\project-1\olist_order_payments_dataset.csv")
file4.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [29]:
file4.duplicated().sum()

0

In [30]:
file4.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [31]:
file4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

In [38]:
file5=pd.read_csv(r"C:\Users\SATHVIK\OneDrive\Desktop\project-1\olist_order_reviews_dataset.csv")
file5.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [35]:
file5.isnull().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [39]:
#dropping the colummns
file5=file5.drop(["review_comment_message","review_comment_title"],axis=1)

In [40]:
file5.columns

Index(['review_id', 'order_id', 'review_score', 'review_creation_date',
       'review_answer_timestamp'],
      dtype='object')

In [41]:
file5.duplicated().sum()

0

In [42]:
file6=pd.read_csv(r"C:\Users\SATHVIK\OneDrive\Desktop\project-1\olist_orders_dataset.csv")
file6.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [43]:
file6.duplicated().sum()

0

In [44]:
file6.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [49]:
file6["order_status"].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [51]:
file7=pd.read_csv(r"C:\Users\SATHVIK\OneDrive\Desktop\project-1\olist_products_dataset.csv")
file7.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [52]:
file7.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [53]:
file7.duplicated().sum()

0

In [59]:
#rename the marks
file7=file7.rename(columns={"product_name_lenght":"product_name_length"})
file7=file7.rename(columns={"product_name_lenght":"product_name_length"})

In [60]:
file7.columns

Index(['product_id', 'product_category_name', 'product_name_length',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'],
      dtype='object')

In [62]:
#only filter columns
file7[file7["product_photos_qty"].isnull()] #same rows

,product_id,product_category_name,product_name_length,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
105,a41e356c76fab66334f36de622ecbd3a,NaN,NaN,NaN,NaN,650.0,17.0,14.0,12.0
128,d8dee61c2034d6d075997acef1870e9b,NaN,NaN,NaN,NaN,300.0,16.0,7.0,20.0
145,56139431d72cd51f19eb9f7dae4d1617,NaN,NaN,NaN,NaN,200.0,20.0,20.0,20.0
154,46b48281eb6d663ced748f324108c733,NaN,NaN,NaN,NaN,18500.0,41.0,30.0,41.0
197,5fb61f482620cb672f5e586bb132eae9,NaN,NaN,NaN,NaN,300.0,35.0,7.0,12.0
...,...,...,...,...,...,...,...,...,...
32515,b0a0c5dd78e644373b199380612c350a,NaN,NaN,NaN,NaN,1800.0,30.0,20.0,70.0
32589,10dbe0fbaa2c505123c17fdc34a63c56,NaN,NaN,NaN,NaN,800.0,30.0,10.0,23.0
32616,bd2ada37b58ae94cc838b9c0569fecd8,NaN,NaN,NaN,NaN,200.0,21.0,8.0,16.0
32772,fa51e914046aab32764c41356b9d4ea4,NaN,NaN,NaN,NaN,1300.0,45.0,16.0,45.0
32852,c4ceee876c82b8328e9c293fa0e1989b,NaN,NaN,NaN,NaN,700.0,28.0,3.0,43.0

In [63]:
file7.shape

(32951, 9)

In [66]:
#drop those useless columns (only null values)
file7=file7.dropna(subset=['product_category_name', 'product_name_length',
       'product_description_lenght', 'product_photos_qty'])

In [67]:
file7.isnull().sum()

product_id                    0
product_category_name         0
product_name_length           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              1
product_length_cm             1
product_height_cm             1
product_width_cm              1
dtype: int64

In [68]:
file7=file7.dropna(subset=["product_length_cm","product_height_cm","product_width_cm"])

In [69]:
file7.isnull().sum()

product_id                    0
product_category_name         0
product_name_length           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
dtype: int64

In [70]:
file7.shape

(32340, 9)

In [72]:
#next file
file8=pd.read_csv(r"C:\Users\SATHVIK\OneDrive\Desktop\project-1\olist_sellers_dataset.csv")
file8.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [73]:
file8.isnull().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [74]:
file8.duplicated().sum()

0

In [75]:
file9=pd.read_csv(r"C:\Users\SATHVIK\OneDrive\Desktop\project-1\product_category_name_translation.csv")
file9.head()

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [76]:
file9.duplicated().sum()

0

In [77]:
file9.isnull().sum()

product_category_name            0
product_category_name_english    0
dtype: int64

In [78]:
file9=file9.rename(columns={"product_category_name_english":"product_english"})

In [79]:
file9.columns

Index(['product_category_name', 'product_english'], dtype='object')

In [81]:
#now loading all tables into mysql database
# Step 1: Import libraries
import pandas as pd
from sqlalchemy import create_engine

# Step 2: Example - assume file7 is your cleaned dataframe
# (If reading from CSV, use below line instead)
# file7 = pd.read_csv("products_cleaned.csv")

# Step 3: Create SQL connection
username = "root"
password = "Deepika%408985"
host = "localhost"
port = "3306"
database = "brazilian_sales"

engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"
)

# Step 4: Load DataFrame into SQL table
file1.to_sql(
    name="customer_table",   # table name in SQL
    con=engine,
    if_exists="replace",       # options: replace, append, fail
    index=False
)

print("Data successfully loaded into SQL!")

Data successfully loaded into SQL!

In [82]:
#now loading all tables into mysql database
# Step 1: Import libraries
import pandas as pd
from sqlalchemy import create_engine

# Step 2: Example - assume file7 is your cleaned dataframe
# (If reading from CSV, use below line instead)
# file7 = pd.read_csv("products_cleaned.csv")

# Step 3: Create SQL connection
username = "root"
password = "Deepika%408985"
host = "localhost"
port = "3306"
database = "brazilian_sales"

engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"
)

# Step 4: Load DataFrame into SQL table
file2.to_sql(
    name="geolocation_table",   # table name in SQL
    con=engine,
    if_exists="replace",       # options: replace, append, fail
    index=False
)

print("Data successfully loaded into SQL!")

Data successfully loaded into SQL!

In [83]:
#now loading all tables into mysql database
# Step 1: Import libraries
import pandas as pd
from sqlalchemy import create_engine

# Step 2: Example - assume file7 is your cleaned dataframe
# (If reading from CSV, use below line instead)
# file7 = pd.read_csv("products_cleaned.csv")

# Step 3: Create SQL connection
username = "root"
password = "Deepika%408985"
host = "localhost"
port = "3306"
database = "brazilian_sales"

engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"
)

# Step 4: Load DataFrame into SQL table
file3.to_sql(
    name="order_items_table",   # table name in SQL
    con=engine,
    if_exists="replace",       # options: replace, append, fail
    index=False
)

print("Data successfully loaded into SQL!")

Data successfully loaded into SQL!

In [84]:
#now loading all tables into mysql database
# Step 1: Import libraries
import pandas as pd
from sqlalchemy import create_engine

# Step 2: Example - assume file7 is your cleaned dataframe
# (If reading from CSV, use below line instead)
# file7 = pd.read_csv("products_cleaned.csv")

# Step 3: Create SQL connection
username = "root"
password = "Deepika%408985"
host = "localhost"
port = "3306"
database = "brazilian_sales"

engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"
)

# Step 4: Load DataFrame into SQL table
file4.to_sql(
    name="order_payments",   # table name in SQL
    con=engine,
    if_exists="replace",       # options: replace, append, fail
    index=False
)

print("Data successfully loaded into SQL!")

Data successfully loaded into SQL!

In [85]:
#now loading all tables into mysql database
# Step 1: Import libraries
import pandas as pd
from sqlalchemy import create_engine

# Step 2: Example - assume file7 is your cleaned dataframe
# (If reading from CSV, use below line instead)
# file7 = pd.read_csv("products_cleaned.csv")

# Step 3: Create SQL connection
username = "root"
password = "Deepika%408985"
host = "localhost"
port = "3306"
database = "brazilian_sales"

engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"
)

# Step 4: Load DataFrame into SQL table
file5.to_sql(
    name="order_reviews",   # table name in SQL
    con=engine,
    if_exists="replace",       # options: replace, append, fail
    index=False
)

print("Data successfully loaded into SQL!")

Data successfully loaded into SQL!

In [86]:
#now loading all tables into mysql database
# Step 1: Import libraries
import pandas as pd
from sqlalchemy import create_engine

# Step 2: Example - assume file7 is your cleaned dataframe
# (If reading from CSV, use below line instead)
# file7 = pd.read_csv("products_cleaned.csv")

# Step 3: Create SQL connection
username = "root"
password = "Deepika%408985"
host = "localhost"
port = "3306"
database = "brazilian_sales"

engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"
)

# Step 4: Load DataFrame into SQL table
file6.to_sql(
    name="orders_table",   # table name in SQL
    con=engine,
    if_exists="replace",       # options: replace, append, fail
    index=False
)

print("Data successfully loaded into SQL!")

Data successfully loaded into SQL!

In [87]:
#now loading all tables into mysql database
# Step 1: Import libraries
import pandas as pd
from sqlalchemy import create_engine

# Step 2: Example - assume file7 is your cleaned dataframe
# (If reading from CSV, use below line instead)
# file7 = pd.read_csv("products_cleaned.csv")

# Step 3: Create SQL connection
username = "root"
password = "Deepika%408985"
host = "localhost"
port = "3306"
database = "brazilian_sales"

engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"
)

# Step 4: Load DataFrame into SQL table
file7.to_sql(
    name="products_table",   # table name in SQL
    con=engine,
    if_exists="replace",       # options: replace, append, fail
    index=False
)

print("Data successfully loaded into SQL!")

Data successfully loaded into SQL!

In [88]:
#now loading all tables into mysql database
# Step 1: Import libraries
import pandas as pd
from sqlalchemy import create_engine

# Step 2: Example - assume file7 is your cleaned dataframe
# (If reading from CSV, use below line instead)
# file7 = pd.read_csv("products_cleaned.csv")

# Step 3: Create SQL connection
username = "root"
password = "Deepika%408985"
host = "localhost"
port = "3306"
database = "brazilian_sales"

engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"
)

# Step 4: Load DataFrame into SQL table
file8.to_sql(
    name="sellers_table",   # table name in SQL
    con=engine,
    if_exists="replace",       # options: replace, append, fail
    index=False
)

print("Data successfully loaded into SQL!")

Data successfully loaded into SQL!

In [89]:
#now loading all tables into mysql database
# Step 1: Import libraries
import pandas as pd
from sqlalchemy import create_engine

# Step 2: Example - assume file7 is your cleaned dataframe
# (If reading from CSV, use below line instead)
# file7 = pd.read_csv("products_cleaned.csv")

# Step 3: Create SQL connection
username = "root"
password = "Deepika%408985"
host = "localhost"
port = "3306"
database = "brazilian_sales"

engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"
)

# Step 4: Load DataFrame into SQL table
file9.to_sql(
    name="english_translation",   # table name in SQL
    con=engine,
    if_exists="replace",       # options: replace, append, fail
    index=False
)

print("Data successfully loaded into SQL!")

Data successfully loaded into SQL!